### ISSUE TITLE
Any number followed by dot converts text to numbered list

### ISSUE THREAD

**Issue by zadam** [ckeditor/ckeditor5-autoformat#60]
How to reproduce: Type "15. " on new line, after space this is converted to numbered list starting with 1. Actual number doesn't matter.

This is pretty annoying for typing e.g. dates (DD. MM. YYYY). According to the docs - https://ckeditor.com/docs/ckeditor5/latest/features/autoformat.html - this autoformat should be triggered only for number 1, which makes sense to me and would mitigate this a great deal (of course you still get occasional unintended autoformat for e.g. dates like 1. 12. 2018).

**Comment by Reinmar** [comment]
Out of curiosity, how does it work in other editors (GDocs, Word, etc.)?

**Comment by wwalc** [comment]
MS Word, Google Docs - `15. ` is not converted into a list. It looks like only `1. ` works there. I'd say the issue is valid.

**Comment by wwalc** [comment]
Btw. I found this old thread: https://github.com/ckeditor/ckeditor5-autoformat/pull/43#discussion_r154004536 which explains why we implemented it this way. I'd say the reasoning there was wrong - in order to help in an edge case  we simply introduced an irritating behavior (after all if one wants to create several list items, then it's normal to press enter once after the last list item, that's all).

**Comment by Reinmar** [comment]
Fine. Adding to the next iteration.

**Comment by pomek** [comment]
Just to be sure – should only `1. ` trigger the action?
